{
 "title": "SRE Demo Dashboard",
 "panels": [
  {
   "title": "Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(api_requests_total[1m])" }
   ]
  },
  {
   "title": "Error Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(api_errors_total[1m])" }
   ]
  },
  {
   "title": "Response Time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "api_request_duration_seconds" }
   ]
  }
 ]
}